apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-pgb0
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0048-tenant/tkrw-pr712-0075-0048-app/devfile-sample-pgb0@sha256:991cdd4694ecaddb248170aa93c3cc0870b41f0ed21cdd6d28759af1c9227559
        name: my-nodejs
        resources: {}
status: {}
